import type { Metadata } from 'next';
import './globals.css';
import StyledComponentsRegistry from '@/lib/registry';
import Setting from '@/components/Setting';

export const metadata: Metadata = {
  title: 'nextjs-project01',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <StyledComponentsRegistry>
          <Setting>{children}</Setting>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
